CC = g++
CFLAGS = -std=c++17

# Build all targets
all: exo1 exo2 exo3 

exo1: exo1.cpp
	$(CC) $(CFLAGS) -o exo1 exo1.cpp

exo2: exo2.cpp
	$(CC) $(CFLAGS) -o exo2 exo2.cpp

exo3: exo3.cpp
	$(CC) $(CFLAGS) -o exo3 exo3.cpp


# Clean command
clean:
	del /f /q exo1.exe exo2.exe exo3.exe 