# Variables
CC = g++
CFLAGS = -std=c++17

# Build all targets
all: exo1 exo2 exo3 exo4 exo5 exo6 exo7

exo1: exo1.cpp
	$(CC) $(CFLAGS) -o exo1 exo1.cpp

exo2: exo2.cpp
	$(CC) $(CFLAGS) -o exo2 exo2.cpp

exo3: exo3.cpp
	$(CC) $(CFLAGS) -o exo3 exo3.cpp

exo4: exo4.cpp
	$(CC) $(CFLAGS) -o exo4 exo4.cpp

exo5: exo5.cpp
	$(CC) $(CFLAGS) -o exo5 exo5.cpp

exo6: exo6.cpp
	$(CC) $(CFLAGS) -o exo6 exo6.cpp

exo7: exo7.cpp
	$(CC) $(CFLAGS) -o exo7 exo7.cpp
# Clean command
clean:
	del /f /q *.exe 

